# =============================================================================
# Consul Manager - 命名空间
# =============================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: consul-mgr
  labels:
    app.kubernetes.io/name: consul-mgr
